# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'challengeCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftLint'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AFNetworking'
  pod 'JGProgressHUD'
  pod 'iOSCommonUI', '~> 1.2'
end

